---
- name: stop apache
  hosts: sai-slave     #group name
  gather_facts: true
  remote_user: root
  become: true
  tesks:
    - name: Install Apache
      yum:
        name: httpd
        state: latest
    - name: stop apache
      service:
        name: httpd
        state: stopped
    -name: Write Content
      content: "Hello This is Devops Team.......!"
      dest: /var/www/html/index.html